### ISSUE TITLE
error loading sound8.npy

### ISSUE THREAD

**Issue by zmahoor** [pseeth/soundnet_keras#1]
Hi, 
I tried loading the pretrained model in sound8.npy and got this error. What could be the problem? python version? tensorflow version?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zahra/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'sound8.npy' as a pickle
```

**Comment by pseeth** [comment]
Works for me in Python 2.7. Try that instead of Python 3? The latest tensorflow and numpy versions seem to work fine for this.

**Comment by pseeth** [comment]
Also, just realized I forgot to commit the categories folder which is needed when you run "python soundnet.py" to test the code.

**Comment by zmahoor** [comment]
yes. I noticed categories folder is missing. Does it mean I have to reinstall the tensorflow with python 2.7? Thanks.

**Comment by pseeth** [comment]
I committed the categories folder. Hm, probably? You could also launch Python2.7 and read the soundnet8.npy file in and then write it back out as a Python3 compatible file. I'm not sure why it isn't compatible as is, though.

**Comment by zmahoor** [comment]
I re-cloned your repo and used np.load('models/sound8.npy', encoding='latin1') with python 3. and it worked! thanks for the help!

**Comment by pseeth** [comment]
Great! No problem.
